SELECT ?item (SAMPLE(?ta98) AS ?TA98) (SAMPLE(?ta2) AS ?TA2) (SAMPLE(?tr) AS ?TR) (SAMPLE(?en) AS ?EN) (SAMPLE(?la) AS ?LA) (GROUP_CONCAT(DISTINCT ?trAlt; separator="|") AS ?TRALT) (GROUP_CONCAT(DISTINCT ?enAlt; separator="|") AS ?ENALT) (SAMPLE(?trDesc) AS ?TRDESC) WHERE { ?item wdt:P1323|wdt:P7173 ?anyId . ?item rdfs:label ?tr FILTER(LANG(?tr)="tr") OPTIONAL{?item wdt:P1323 ?ta98} OPTIONAL{?item wdt:P7173 ?ta2} OPTIONAL{?item rdfs:label ?en FILTER(LANG(?en)="en")} OPTIONAL{?item rdfs:label ?la FILTER(LANG(?la)="la")} OPTIONAL{?item skos:altLabel ?trAlt FILTER(LANG(?trAlt)="tr")} OPTIONAL{?item skos:altLabel ?enAlt FILTER(LANG(?enAlt)="en")} OPTIONAL{?item schema:description ?trDesc FILTER(LANG(?trDesc)="tr")} } GROUP BY ?item
