const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http');
const {chromium}=require('C:/Users/sevdi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const live=process.argv.includes('--live'),results=[],errors=[],requests=[];let browser,server,origin=(process.env.BILGE_TEST_ORIGIN||'http://100.84.251.49:18788');
async function saved(p){await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Bu cihazda kaydedildi')}
async function data(p){return p.evaluate(()=>dbGet())}
async function tools(p){if(!await p.locator('#toolsDialog').evaluate(d=>d.open))await p.locator('#toolsToggle').tap()}
async function closeTools(p){if(await p.locator('#toolsDialog').evaluate(d=>d.open))await p.locator('#toolsClose').click()}
async function openPdf(p){await tools(p);await p.locator('#pdfOpen').click()}
async function readyPdf(p){await p.waitForFunction(()=>pdfBackgroundReady())}
async function stroke(p,from=[110,130],to=[310,130]){const r=await p.locator('#canvas').boundingBox();await p.mouse.move(r.x+from[0],r.y+from[1]);await p.mouse.down();await p.mouse.move(r.x+to[0],r.y+to[1],{steps:12});await p.mouse.up();await saved(p)}
async function pixels(p,id){return p.locator(id).evaluate(c=>{const a=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let n=0;for(let i=0;i<a.length;i++)n=(n+a[i])>>>0;return n})}
async function sidebar(p){if(!await p.locator('#pageSidebar').isVisible())await p.locator('#sidebarToggle').tap()}
async function download(p){await tools(p);const next=p.waitForEvent('download');await p.locator('#exportBtn').click();const b=JSON.parse(await fs.readFile(await (await next).path(),'utf8'));await closeTools(p);return b}
async function restoreBackup(p,b){await p.locator('#importFile').setInputFiles({name:'pdf-notes.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(b))});await p.locator('#backupApply').click();await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Yedek geri yüklendi');await readyPdf(p)}
async function invalid(p,b){const before=await data(p),next=p.waitForEvent('dialog');await p.locator('#importFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(b))});const d=await next;assert.match(d.message(),/Geçerli/);await d.accept();assert.deepEqual(await data(p),before)}
(async()=>{
 if(!live){server=http.createServer(async(req,res)=>{try{const file=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(file.includes('..'))throw Error();const bytes=await fs.readFile(path.join(__dirname,'bilge-defter-test',file==='/'?'index.html':file));const ext=path.extname(file);res.setHeader('Content-Type',({'.css':'text/css','.js':'application/javascript','.mjs':'application/javascript','.html':'text/html','.wasm':'application/wasm'})[ext]||'text/html');res.end(bytes)}catch{res.statusCode=404;res.end()}});await new Promise(ok=>server.listen(0,'127.0.0.1',ok));origin=`http://127.0.0.1:${server.address().port}`}
 browser=await chromium.launch({headless:true});const c=await browser.newContext({viewport:{width:1180,height:820},hasTouch:true,serviceWorkers:'block'});c.on('request',r=>requests.push({url:r.url(),method:r.method()}));const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(45000);await p.goto(origin+'/?v=20');await saved(p);await stroke(p);const original=await data(p);
 await openPdf(p);await p.locator('#pdfFile').setInputFiles({name:'broken.pdf',mimeType:'application/pdf',buffer:Buffer.from('Not a PDF')});await p.waitForFunction(()=>!pdfBusy);assert.match(await p.locator('#pdfProgress').innerText(),/PDF eklenmedi/);assert.deepEqual(await data(p),original);assert.equal(await p.locator('#pdfApply').isDisabled(),true);
 await p.locator('#pdfFile').setInputFiles({name:'large.pdf',mimeType:'application/pdf',buffer:Buffer.alloc(20*1024*1024+1)});await p.waitForFunction(()=>!pdfBusy);assert.match(await p.locator('#pdfProgress').innerText(),/20 MB/);await p.locator('#pdfClose').click();assert.deepEqual(await data(p),original);
 results.push('Malformed and oversized PDF do not change existing ink or disk data; cancel closes safely');
 const sample=await fs.readFile(path.join(__dirname,'pdf-dependency/sample.pdf'));const offsets=[...sample.toString('latin1').matchAll(/startxref\s+(\d+)/g)];assert.ok(offsets.length);const footer=Buffer.from('\nstartxref\n'+offsets.at(-1)[1]+'\n%%EOF\n');const boundary=Buffer.concat([sample,Buffer.alloc(20*1024*1024-sample.length-footer.length,32),footer]);assert.equal(boundary.length,20*1024*1024);
 await openPdf(p);const chooser=p.waitForEvent('filechooser');await p.locator('#pdfChoose').click();await (await chooser).setFiles({name:'boundary-20MiB.pdf',mimeType:'application/pdf',buffer:boundary});await p.waitForFunction(()=>!!pdfPending&&!pdfBusy,{},{timeout:60000});assert.equal(await p.evaluate(()=>pdfPending.pages.length),14);assert.deepEqual(await data(p),original);assert.equal(await p.evaluate(()=>canEdit()),false);
 results.push('Exact 20 MiB PDF with padding is accepted and 14 pages render; this tests byte boundary, not image-heavy tablet performance; preview remains nonmutating');
 await p.evaluate(()=>{window.__put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...a){const r=window.__put.apply(this,a);if(a[1]==='app')this.transaction.abort();return r}});await p.locator('#pdfApply').click();await p.waitForFunction(()=>!pdfBusy);assert.match(await p.locator('#pdfProgress').innerText(),/mevcut notlar korundu/);assert.deepEqual(await data(p),original);assert.equal(await p.locator('#pdfApply').isEnabled(),true);await p.evaluate(()=>IDBObjectStore.prototype.put=window.__put);await p.locator('#pdfApply').click();await saved(p);await readyPdf(p);let b=await data(p);assert.equal(b.version,2);assert.equal(b.pages.length,15);assert.deepEqual(b.pages[0],original.pages[0]);assert.equal(b.pages[1].pdf.total,14);assert.equal(await p.locator('#pdfPrevious').isDisabled(),true);assert.match(await p.locator('#pdfPageLabel').innerText(),/1\/14/);assert.ok(await pixels(p,'#pdfCanvas')>1000000);const first=b.active;
 results.push('Failed PDF add is atomic with retry; successful add creates a separate notebook and preserves old pages; schema 2 protects against old application writes');
 const background=await pixels(p,'#pdfCanvas');await stroke(p);const pen=await pixels(p,'#canvas');assert.ok(pen>0);await tools(p);await p.locator('[data-tool="marker"]').click();await closeTools(p);await stroke(p,[120,170],[310,170]);assert.ok(await pixels(p,'#canvas')>pen);await p.locator('#quickTool').tap();await stroke(p,[200,110],[200,190]);assert.equal(await pixels(p,'#pdfCanvas'),background);b=await data(p);assert.deepEqual(b.pages.find(x=>x.id===first).strokes.map(s=>s.tool),['pen','marker','eraser']);const ink=b.pages.find(x=>x.id===first).strokes,inkPixels=await pixels(p,'#canvas');await p.reload();await saved(p);await readyPdf(p);assert.equal(await pixels(p,'#canvas'),inkPixels);assert.equal(await pixels(p,'#pdfCanvas'),background);
 results.push('Pen, highlighter and eraser modify only transparent ink; original PDF pixels and stored annotations survive reload');
 await p.locator('#pdfNext').tap();await saved(p);await readyPdf(p);assert.equal(await pixels(p,'#canvas'),0);await stroke(p);const second=(await data(p)).active;await p.locator('#pdfPrevious').tap();await saved(p);await readyPdf(p);assert.equal((await data(p)).active,first);assert.deepEqual((await data(p)).pages.find(x=>x.id===first).strokes,ink);
 const scale=await p.evaluate(()=>paperScale());await p.locator('#canvas').evaluate(c=>{const r=c.getBoundingClientRect();const send=(type,id,y)=>c.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerId:id,pointerType:'touch',clientX:r.x+100+id,clientY:r.y+y}));send('pointerdown',21,400);send('pointerdown',22,400);send('pointermove',21,200);send('pointermove',22,200);send('pointerup',21,200);send('pointerup',22,200)});await saved(p);assert.ok(Math.abs(await p.evaluate(()=>viewY())-200/scale)<1);assert.deepEqual((await data(p)).pages.find(x=>x.id===first).strokes,ink);await p.evaluate(()=>{scrollPaper(0);return flushSave()});await p.setViewportSize({width:820,height:1180});await readyPdf(p);assert.deepEqual((await data(p)).pages.find(x=>x.id===first).strokes,ink);const relative=await p.evaluate(()=>{const s=page().strokes[0];return {x:s.points[0].x*paperScale(),scale:paperScale()}});assert.ok(relative.x<110);assert.equal((await data(p)).pages.find(x=>x.id===second).strokes.length,1);
 results.push('Page navigation isolates notes; two-finger pan changes PDF and ink in shared document coordinates; rotation preserves stored alignment');
 const backup=await download(p);assert.equal(backup.backupVersion,4);assert.equal(backup.version,2);await restoreBackup(p,{version:1,pages:[{id:'empty',title:'Boş',strokes:[]}],active:'empty'});await restoreBackup(p,backup);await p.reload();await saved(p);await readyPdf(p);assert.deepEqual((await data(p)).pages,backup.pages);
 await tools(p);p.once('dialog',d=>d.accept());await p.locator('#clearPage').click();await saved(p);assert.equal(await pixels(p,'#canvas'),0);const cleared=await data(p),copy=cleared.trash[0];assert.deepEqual(copy.page.pdf,backup.pages.find(x=>x.id===first).pdf);await sidebar(p);await p.locator('#openTrash').tap();await p.locator('#trashList').getByRole('button',{name:'Geri getir',exact:true}).first().click();await saved(p);await readyPdf(p);assert.deepEqual((await data(p)).pages.find(x=>x.id===copy.page.id).pdf,copy.page.pdf);assert.deepEqual((await data(p)).pages.find(x=>x.id===copy.page.id).strokes,ink);
 results.push('Format-4 JSON round-trip preserves PDF backgrounds and ink; clear affects only ink and Trash restores a complete independent PDF page');
 for(const change of [{image:'https://example.com/image.png'},{width:200000},{height:1},{number:99},{total:100},{image:'data:image/png;base64,aGVsbG8='}]){const bad=JSON.parse(JSON.stringify(backup));Object.assign(bad.pages[1].pdf,change);await invalid(p,bad)}await invalid(p,{...backup,version:1});
 results.push('Remote backgrounds, malformed PNG, unsafe dimensions, invalid page metadata and downgrade to old schema are rejected without overwriting notes');
 await p.setViewportSize({width:390,height:844});await readyPdf(p);for(const id of ['#pdfPrevious','#pdfNext','#pdfPageLabel']){const r=await p.locator(id).boundingBox();assert.ok(r.x>=0&&r.x+r.width<=390)}await p.screenshot({path:path.join(__dirname,`bilge-defter-v43-pdf-${live?'live':'local'}.png`),fullPage:true});assert.equal(requests.some(r=>r.method!=='GET'),false);assert.equal(requests.some(r=>!r.url.startsWith(origin)&&!r.url.startsWith('data:')&&!r.url.startsWith('blob:')),false);assert.deepEqual(errors,[]);
 results.push('Narrow PDF navigation fits touch layout; observed PDF flow sends no document upload or third-party network request');
 const beforeCorrupt=await data(p),bad=JSON.parse(JSON.stringify(backup));bad.pages[1].pdf.image=bad.pages[1].pdf.image.slice(0,66);const badDialog=p.waitForEvent('dialog');await p.locator('#importFile').setInputFiles({name:'truncated.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});const rejected=await badDialog;assert.match(rejected.message(),/PDF görüntüsü okunamadı/);await rejected.accept();assert.deepEqual(await data(p),beforeCorrupt);
 results.push('Truncated PNG with a plausible header is decoded and rejected before backup replacement; existing notes remain intact');
 await p.setViewportSize({width:1180,height:820});await openPdf(p);await p.locator('#pdfFile').setInputFiles(path.join(__dirname,'pdf-dependency/sample.pdf'));await p.locator('#pdfClose').click();await p.waitForFunction(()=>!pdfBusy);assert.deepEqual(await data(p),beforeCorrupt);await openPdf(p);assert.equal(await p.locator('#pdfApply').isDisabled(),true);await p.locator('#pdfClose').click();
 results.push('Cancelling real PDF preparation cannot add late pages or leave the editor locked');
 const right=await c.newPage();right.on('pageerror',e=>errors.push(e.message));await right.goto(origin+'/?v=20');await saved(right);await openPdf(right);await right.locator('#pdfFile').setInputFiles(path.join(__dirname,'pdf-dependency/sample.pdf'));await right.waitForFunction(()=>!!pdfPending&&!pdfBusy,{},{timeout:60000});await stroke(p);const winning=await data(p);await right.locator('#pdfApply').click();await right.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('Başka sekmede'));assert.equal(await right.locator('#pdfDialog').isVisible(),false);assert.deepEqual(await data(right),winning);await right.close();
 results.push('New PDF prepared in a stale tab cannot overwrite another tab, nor append a partial notebook');
 const beforeLimit=await data(p);await openPdf(p);await p.locator('#pdfFile').setInputFiles(path.join(__dirname,'pdf-dependency/fixtures/pages-51.pdf'));await p.waitForFunction(()=>!pdfBusy);assert.match(await p.locator('#pdfProgress').innerText(),/en fazla 50 sayfa/);assert.equal(await p.locator('#pdfApply').isDisabled(),true);assert.deepEqual(await data(p),beforeLimit);
 results.push('Actual 51-page PDF is rejected at page-count boundary without changing current notes');
 await p.locator('#pdfFile').setInputFiles(path.join(__dirname,'pdf-dependency/fixtures/pages-50.pdf'));await p.waitForFunction(()=>!!pdfPending&&!pdfBusy,{},{timeout:60000});assert.equal(await p.evaluate(()=>pdfPending.pages.length),50);await p.locator('#pdfApply').click();await saved(p);await readyPdf(p);let fifty=await data(p);const notebook=fifty.activeNotebook;assert.equal(fifty.pages.filter(x=>x.notebookId===notebook).length,50);await sidebar(p);await p.locator('#pages .page-item').last().locator('button').first().tap();await saved(p);await readyPdf(p);assert.match(await p.locator('#pdfPageLabel').innerText(),/50\/50/);assert.equal(await p.locator('#pdfNext').isDisabled(),true);await stroke(p);fifty=await data(p);const lastId=fifty.active;await p.reload();await saved(p);await readyPdf(p);assert.equal((await data(p)).active,lastId);assert.equal((await data(p)).pages.find(x=>x.id===lastId).strokes.length,1);const fiftyBackup=await download(p);await restoreBackup(p,{version:1,pages:[{id:'reset',title:'Reset',strokes:[]}],active:'reset'});await restoreBackup(p,fiftyBackup);assert.deepEqual((await data(p)).pages,fiftyBackup.pages);await p.screenshot({path:path.join(__dirname,`bilge-defter-v43-limit50-${live?'live':'local'}.png`),fullPage:true});
 results.push('Actual 50-page synthetic PDF is accepted; last-page drawing, reload and full JSON backup restore retain all pages and ink; not tablet performance evidence');
 assert.deepEqual(errors,[]);await c.close();console.log(JSON.stringify({mode:live?'live':'local',passed:results.length,results,physicalTabletTest:'pending'},null,2));
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)await new Promise(ok=>server.close(ok))});
