const fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/sevdi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
let browser,server;const results=[],pass=s=>{results.push(s);console.log('PASS '+s)};
(async()=>{try{
 server=http.createServer(async(req,res)=>{try{const n=new URL(req.url,'http://local').pathname.slice(1)||'index.html',data=await fs.readFile(path.join(__dirname,'bilge-defter-invited-v31',n));res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.wasm':'application/wasm'})[path.extname(n)]||'application/octet-stream'});res.end(data)}catch{res.writeHead(404);res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const origin=process.env.BILGE_TEST_ORIGIN||`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch({headless:true});const c=await browser.newContext({viewport:{width:1180,height:900},timezoneId:'Europe/Istanbul'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.waitForFunction(()=>ready);await p.waitForFunction(()=>document.querySelector('#pwaStatus').textContent.includes('paket hazır'));
 async function saved(){await p.waitForFunction(()=>!isDirty()&&!savePromise&&!saveFailed&&!saveConflict)}
 async function open(){await p.locator('#toolsToggle').click();await p.locator('#plannerOpen').click();await p.locator('#plannerDialog').waitFor()}
 async function go(date){await p.locator('#plannerDay').fill(date);await p.locator('#plannerDay').dispatchEvent('change')}
 async function add({title='Anatomi tekrarı',date='2028-02-29',time='09:00',minutes='45',kind='study',notes='Üst ekstremite',notebook='general'}={}){await p.locator('#plannerNew').click();await p.locator('#plannerName').fill(title);await p.locator('#plannerDate').fill(date);await p.locator('#plannerTime').fill(time);await p.locator('#plannerMinutes').fill(minutes);await p.locator('#plannerKind').selectOption(kind);await p.locator('#plannerNotes').fill(notes);await p.locator('#plannerNotebook').selectOption(notebook);await p.locator('#plannerSubmit').click();await saved()}
 const card=id=>p.locator(`.planner-item[data-id="${id}"]`);
 async function restore(book){await p.locator('#importFile').setInputFiles({name:'planner.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(book))});await p.locator('#backupApply').click();await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Yedek geri yüklendi')}
 const original=await p.evaluate(()=>dbGet());await open();assert.equal(await p.evaluate(()=>canEdit()),false);assert.equal(await p.evaluate(()=>state.planner),undefined);await p.locator('#plannerClose').click();assert.deepEqual(await p.evaluate(()=>dbGet()),original);pass('Opening and closing the calendar leaves old notebook data unchanged and blocks drawing while modal is open');
 await open();await go('2028-02-29');assert.match(await p.locator('#plannerMonthTitle').textContent(),/Şubat 2028/);assert.equal(await p.locator('#plannerGrid button[data-date="2028-02-29"]').getAttribute('aria-pressed'),'true');await p.locator('#plannerNext').click();assert.match(await p.locator('#plannerMonthTitle').textContent(),/Mart 2028/);await p.locator('#plannerPrev').click();assert.match(await p.locator('#plannerMonthTitle').textContent(),/Şubat 2028/);pass('Leap day and month navigation use civil calendar dates');
 await add({title:'Anatomi <img src=x onerror=alert(1)>',notes:'Türkçe: ığüşöç\nBölüm 3'});const first=await p.evaluate(()=>state.planner.items[0]);assert.equal(await p.evaluate(()=>state.version),5);assert.equal(await p.locator('img[src=x]').count(),0);assert.deepEqual((await p.evaluate(()=>dbGet())).pages[0].strokes,original.pages[0].strokes);pass('Study creation stores title, notes, local date, time, duration and notebook without changing ink or executing HTML');
 await add({title:'Anatomi dersi',kind:'lesson',time:'08:00',minutes:'60'});const lesson=await p.evaluate(()=>state.planner.items[1]);assert.equal(await p.locator('.planner-item').first().getAttribute('data-id'),lesson.id);assert.match(await p.locator('#plannerSummary').textContent(),/105 dk planlandı/);assert.match(await p.locator('#plannerGrid button[data-date="2028-02-29"]').getAttribute('aria-label'),/2 kayıt/);pass('Lessons and study tasks sort by time, populate day badges and total planned minutes');
 await card(first.id).getByRole('button',{name:'Tamamlandı',exact:true}).click();await saved();assert.equal(await p.evaluate(()=>state.planner.items[0].done),true);assert.match(await p.locator('#plannerSummary').textContent(),/1 tamamlandı/);await p.locator('#plannerClose').click();await p.reload();await p.waitForFunction(()=>ready);await open();await go('2028-02-29');assert.equal(await card(first.id).getAttribute('data-done'),'true');pass('Completion survives reload without changing other tasks');
 await card(first.id).getByRole('button',{name:'Düzenle',exact:true}).click();await p.locator('#plannerDate').fill('2028-03-01');await p.locator('#plannerMinutes').fill('90');await p.locator('#plannerSubmit').click();await saved();assert.equal(await p.locator('#plannerDay').inputValue(),'2028-03-01');assert.equal(await p.evaluate(()=>state.planner.items[0].done),true);await go('2028-02-29');assert.equal(await p.locator('.planner-item').count(),1);pass('Editing reschedules the same task, retains completion and refreshes both calendar days');
 await card(lesson.id).getByRole('button',{name:'Deftere git'}).click();assert.equal(await p.locator('#plannerDialog').evaluate(d=>d.open),false);assert.equal(await p.evaluate(()=>activeNotebook),'general');await saved();pass('Linked notebook opens from the planner and returns to editable notes');
 await open();const beforeDraft=await p.evaluate(()=>dbGet());await p.locator('#plannerNew').click();await p.locator('#plannerName').fill('Kaydedilmeyecek');p.once('dialog',d=>d.dismiss());await p.locator('#plannerClose').click();assert.equal(await p.locator('#plannerForm').isVisible(),true);assert.equal(await p.locator('#plannerName').inputValue(),'Kaydedilmeyecek');p.once('dialog',d=>d.accept());await p.keyboard.press('Escape');assert.deepEqual(await p.evaluate(()=>dbGet()),beforeDraft);pass('Unsaved form close warns, cancellation preserves the draft and confirmed Escape discards without writing');
 await open();await go('2028-02-29');await card(lesson.id).getByRole('button',{name:'Sil',exact:true}).click();await saved();assert.equal(await p.evaluate(()=>state.planner.items.length),1);assert.equal(await p.evaluate(()=>state.planner.trash[0].item.id),lesson.id);await p.locator('#plannerClose').click();await p.reload();await p.waitForFunction(()=>ready);await open();await p.locator('#plannerArchiveToggle').click();await card(lesson.id).getByRole('button',{name:'Geri getir'}).click();await saved();assert.equal(await p.evaluate(()=>state.planner.items.length),2);assert.equal(await p.evaluate(()=>state.planner.trash.length),0);pass('Deletion archives the full task; archive survives reload and restores the same identity');
 await go('2028-02-29');await card(lesson.id).getByRole('button',{name:'Sil',exact:true}).click();await saved();const backupEvent=p.waitForEvent('download');await p.locator('#plannerExport').click();const backup=JSON.parse(await fs.readFile(await(await backupEvent).path(),'utf8'));assert.equal(backup.backupVersion,7);assert.equal(backup.planner.trash.length,1);assert.equal(backup.planner.items.length,1);pass('Actual downloaded JSON backup v7 includes active and archived plans');
 await p.locator('#plannerArchiveToggle').click();p.once('dialog',d=>d.dismiss());await card(lesson.id).getByRole('button',{name:'Kalıcı sil'}).click();assert.equal(await p.evaluate(()=>state.planner.trash.length),1);p.once('dialog',d=>d.accept());await card(lesson.id).getByRole('button',{name:'Kalıcı sil'}).click();await saved();assert.equal(await p.evaluate(()=>state.planner.trash.length),0);pass('Permanent deletion requires confirmation and affects only the selected archived task');
 await p.locator('#plannerClose').click();await restore(backup);assert.deepEqual(await p.evaluate(()=>state.planner),backup.planner);await p.locator('#importFile').setInputFiles({name:'old.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(original))});assert.match(await p.locator('#backupWarning').textContent(),/Takvimsiz eski yedek mevcut planları kaldırır/);await p.locator('#backupApply').click();await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Yedek geri yüklendi');assert.equal(await p.evaluate(()=>state.planner),undefined);await p.locator('#toolsToggle').click();p.once('dialog',d=>d.accept());await p.locator('#restorePrevious').click();await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Önceki defter geri getirildi');await p.locator('#toolsClose').click();assert.deepEqual(await p.evaluate(()=>state.planner),backup.planner);pass('Import restores exact plans; old backup replacement warns and pre-import recovery returns the full planner');
 const invalid=await p.evaluate(b=>{const check=fn=>{const x=structuredClone(b);fn(x);return validState(x)};return [check(x=>x.version=4),check(x=>delete x.planner),check(x=>x.planner.items[0].date='2027-02-29'),check(x=>x.planner.items[0].time='25:00'),check(x=>x.planner.items[0].minutes=0),check(x=>x.planner.items[0].title=' '),check(x=>x.planner.trash[0].item.id=x.planner.items[0].id),check(x=>x.planner.items[0].done='true'),check(x=>x.planner.items[0].notebookId={})]},backup);assert.deepEqual(invalid,Array(9).fill(false));pass('Malformed dates, times, durations, duplicate IDs, completion, links and disguised schemas fail closed');
 assert.deepEqual(await p.evaluate(b=>{const item=b.planner.items[0];b.planner={version:1,items:Array.from({length:1000},(_,i)=>({...item,id:'t'+i})),trash:[]};const good=validState(b);b.planner.trash.push({item:{...item,id:'extra'},deletedAt:new Date().toISOString()});return [good,validState(b)]},backup),[true,false]);pass('Combined active/archive limit accepts 1000 unique records and rejects 1001');
 await c.setOffline(true);await open();await add({title:'Çevrim dışı tekrar',date:'2028-03-02'});await p.locator('#plannerClose').click();await p.reload();await p.waitForFunction(()=>ready);await open();await go('2028-03-02');assert.match(await p.locator('#plannerItems').textContent(),/Çevrim dışı tekrar/);await c.setOffline(false);pass('Offline creation, saving and re-opening work with cached planner assets');
 const diskBefore=await p.evaluate(()=>dbGet());await p.evaluate(()=>{window.oldPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...a){const r=window.oldPut.apply(this,a);if(a[1]==='app')this.transaction.abort();return r}});await p.locator('#plannerNew').click();await p.locator('#plannerName').fill('Kayıt hata denemesi');await p.locator('#plannerSubmit').click();await p.waitForFunction(()=>saveFailed);assert.deepEqual(await p.evaluate(()=>dbGet()),diskBefore);assert.match(await p.locator('#plannerSaveState').textContent(),/Kaydedilemedi/);await p.evaluate(()=>IDBObjectStore.prototype.put=window.oldPut);await p.locator('#plannerRetry').click();await saved();assert.equal(await p.evaluate(()=>(state.planner.items.at(-1).title)),'Kayıt hata denemesi');pass('Failed write preserves prior disk data, exposes failure inside planner and retry saves retained task');
 await p.setViewportSize({width:390,height:844});await go('2028-03-02');await p.screenshot({path:path.join(__dirname,'planner-v31-mobile.png')});let rect=await p.locator('#plannerDialog').boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=390&&rect.height<=820);assert.equal(await p.evaluate(()=>plannerDialog.scrollWidth<=plannerDialog.clientWidth),true);await p.locator('#plannerNew').click();await p.locator('#plannerName').fill('Küçük ekranda ders');await p.screenshot({path:path.join(__dirname,'planner-v31-mobile-form.png')});assert.equal(await p.evaluate(()=>plannerDialog.scrollWidth<=plannerDialog.clientWidth),true);p.once('dialog',d=>d.accept());await p.locator('#plannerCancel').click();await p.setViewportSize({width:1180,height:900});await p.screenshot({path:path.join(__dirname,'planner-v31-desktop.png')});pass('390px calendar and editor fit without horizontal scrolling and retain readable touch targets');
 await p.locator('#plannerClose').click();const planBeforeMedia=await p.evaluate(()=>structuredClone(state.planner));await p.keyboard.press('t');await p.locator('#layoutText').fill('Planla birlikte not');await p.locator('#layoutAngle').fill('20');await p.locator('#layoutDone').click();await saved();assert.equal(await p.evaluate(()=>state.version),5);assert.deepEqual(await p.evaluate(()=>state.planner),planBeforeMedia);assert.equal(await p.evaluate(()=>validState(state)),true);pass('Rotated text addition preserves planner schema and every task');
 for(const zone of ['America/Los_Angeles','Pacific/Auckland']){const tz=await browser.newContext({timezoneId:zone}),tp=await tz.newPage();await tp.goto(origin);await tp.waitForFunction(()=>ready);assert.deepEqual(await tp.evaluate(()=>['2028-02-29','2026-03-08','2026-11-01'].map(s=>plannerDateString(plannerDateValue(s)))),['2028-02-29','2026-03-08','2026-11-01']);await tz.close()}pass('Civil dates round-trip in negative and positive UTC-offset zones, including DST transition dates');
 const right=await c.newPage();await right.goto(origin);await right.waitForFunction(()=>ready);await open();await p.locator('#plannerNew').click();await p.locator('#plannerName').fill('Eski sekmenin planı');await right.evaluate(async()=>{page().title='Başka sekme';scheduleSave();await flushSave()});const winner=await right.evaluate(()=>dbGet());await p.locator('#plannerSubmit').click();await p.waitForFunction(()=>saveConflict);assert.deepEqual(await p.evaluate(()=>dbGet()),winner);assert.equal(await p.locator('#plannerSubmit').isDisabled(),true);assert.match(await p.locator('#plannerSaveState').textContent(),/Başka sekmede/);await right.close();pass('Stale-tab plan cannot overwrite newer notes; conflict disables writes and remains visible in the planner');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:results.length,results,physicalTablet:'pending'},null,2));
 }finally{await browser?.close();if(server)await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
