const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http');
const {chromium}=require('C:/Users/sevdi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
let server,browser,mode='v39';const root=path.join(__dirname,'bilge-defter-invited-v39'),oldRoot=path.join(__dirname,'bilge-defter-invited'),results=[];
const mime={'.js':'application/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png','.wasm':'application/wasm'};
const pass=s=>{results.push(s);console.log(s)};
async function saved(p){await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Bu cihazda kaydedildi')}
async function tools(p){if(!await p.locator('#toolsDialog').evaluate(d=>d.open))await p.locator('#toolsToggle').click()}
async function closeTools(p){if(await p.locator('#toolsDialog').evaluate(d=>d.open))await p.locator('#toolsClose').click()}
async function draw(p){const r=await p.locator('#canvas').boundingBox();await p.mouse.move(r.x+100,r.y+130);await p.mouse.down();assert.equal(await p.locator('#quickUndo').isDisabled(),true);await p.mouse.move(r.x+210,r.y+190,{steps:8});await p.mouse.up();await saved(p)}
(async()=>{try{
 server=http.createServer(async(req,res)=>{try{const name=new URL(req.url,'http://local').pathname.slice(1)||'index.html';if(name.includes('..'))throw Error();let data=name==='release.json'&&mode==='offline-release'?null:await fs.readFile(path.join(mode==='v20'?oldRoot:root,name));if(!data){res.writeHead(503);res.end();return}res.writeHead(200,{'Content-Type':mime[path.extname(name)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data)}catch{res.writeHead(404);res.end()}});await new Promise(ok=>server.listen(0,'127.0.0.1',ok));const origin=process.env.BILGE_TEST_ORIGIN||`http://127.0.0.1:${server.address().port}`;
 browser=await chromium.launch({headless:true});const c=await browser.newContext({viewport:{width:1180,height:820},hasTouch:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(20000);await p.goto(origin);await saved(p);await p.waitForFunction(()=>document.querySelector('#pwaStatus').textContent.includes('paket hazır'));
 assert.equal(await p.locator('#quickUndo').isDisabled(),true);const a=await p.locator('#quickUndo').boundingBox(),b=await p.locator('#quickTool').boundingBox();assert.ok(a.y+a.height<=b.y);await draw(p);await p.locator('#quickUndo').click();await saved(p);assert.equal(await p.evaluate(()=>page().strokes.length),0);await p.reload();await saved(p);assert.equal(await p.evaluate(()=>page().strokes.length),0);pass('Quick undo is above eraser, disabled on empty page and during pen input, removes ink and persists');
 await draw(p);const before=await p.evaluate(()=>dbGet());await tools(p);for(const color of ['#183e38','#243c5a','#343b42','#5b3c59','#d8c8ae']){await p.locator(`[data-frame-color="${color}"]`).click();assert.equal(await p.locator(`[data-frame-color="${color}"]`).getAttribute('aria-pressed'),'true');assert.equal(await p.evaluate(()=>document.querySelector('meta[name=theme-color]').content),color)}assert.deepEqual(await p.evaluate(()=>dbGet()),before);await p.reload();await saved(p);assert.equal(await p.evaluate(()=>document.querySelector('meta[name=theme-color]').content),'#d8c8ae');pass('Five frame presets persist across reload without changing page color, ink or saved notebook');
 await tools(p);for(const color of ['#ffffff','#000000','#777777','#d8c8ae']){await p.locator('#frameColor').fill(color);await p.locator('#frameColor').dispatchEvent('input');const ratio=await p.evaluate(()=>{const rgb=s=>s.match(/\d+/g).slice(0,3).map(Number),lum=a=>a.map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4}).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0),h=getComputedStyle(document.querySelector('header')),a=lum(rgb(h.color)),b=lum(rgb(h.backgroundColor));return(Math.max(a,b)+.05)/(Math.min(a,b)+.05)});assert.ok(ratio>=4.5)}pass('Custom dark, light and middle colors maintain at least 4.5:1 header text contrast');
 await p.evaluate(()=>{window.oldSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw Error('simulated full storage')}});await p.locator('[data-frame-color="#243c5a"]').click();assert.match(await p.locator('#appearanceStatus').textContent(),/bu oturumda/);assert.deepEqual(await p.evaluate(()=>dbGet()),before);await p.evaluate(()=>Storage.prototype.setItem=window.oldSet);pass('Blocked preference storage reports session-only color without losing notes');
 await closeTools(p);await p.keyboard.press('t');await p.locator('#layoutText').fill('Anatomi\nÜst ekstremite\n\nDers notları ve tekrar');await p.locator('#layoutDone').click();await saved(p);await p.locator('#quickUndo').click();await saved(p);assert.equal(await p.evaluate(()=>page().strokes.length),1);pass('Quick undo shares the existing text/image history instead of a separate ink-only action');
 await tools(p);assert.deepEqual(await p.locator('.action-group h3').allTextContents(),['EKLE VE DÜZENLE','ÇALIŞMA PLANI','TANIMA','SAYFA İŞLEMLERİ','YEDEK VE KURULUM']);await p.locator('#pwaOpen').click();await p.locator('#pwaCheck').click();await p.waitForFunction(()=>document.querySelector('#pwaUpdate').textContent.includes('Bu adres güncel: v39'));assert.match(await p.locator('#pwaVersion').textContent(),/Bu pencere: v39 · Sunucu: v39/);pass('Update check shows matching current and server version rather than an ambiguous no-package message');
 if(!process.env.BILGE_TEST_ORIGIN){mode='offline-release';await p.locator('#pwaCheck').click();await p.waitForFunction(()=>document.querySelector('#pwaUpdate').textContent.includes('denetlenemedi'));assert.match(await p.locator('#pwaVersion').textContent(),/henüz denetlenmedi/);mode='v39';pass('Server version lookup failure does not claim the application is up to date')}
 await p.locator('#pwaClose').click();await tools(p);await p.locator('[data-frame-color="#183e38"]').click();await closeTools(p);
 for(const [name,width,height] of [['tablet',1180,820],['phone',390,844],['landscape',844,390]]){await p.setViewportSize({width,height});await p.locator('#quickTool').click();const dock=await p.locator('.edge-actions').boundingBox(),work=await p.locator('.workspace').boundingBox();assert.ok(dock.x>=0&&dock.x+dock.width<=width&&dock.y>=work.y&&dock.y+dock.height<=work.y+work.height+.5);for(const id of ['quickUndo','quickTool','eraserSizeToggle','toolsToggle']){const r=await p.locator('#'+id).boundingBox();assert.ok(r.width>=44&&r.height>=44)}await p.screenshot({path:path.join(__dirname,`bilge-defter-v39-${name}.png`),fullPage:true});await tools(p);const d=await p.locator('#toolsDialog').boundingBox();assert.ok(d.x>=0&&d.x+d.width<=width&&d.height<=height-20);await p.locator('#appearanceSection').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(__dirname,`bilge-defter-v39-${name}-appearance.png`),fullPage:true});await closeTools(p);await p.locator('#quickTool').click()}
 pass('Tablet, phone and short landscape fit the dock and theme controls with 44px minimum targets');
 const malformed=await browser.newContext();await malformed.addInitScript(()=>localStorage.setItem('bilge-defter-frame-v1','url(evil)'));const mp=await malformed.newPage();await mp.goto(origin);await saved(mp);assert.equal(await mp.locator('#frameColor').inputValue(),'#183e38');await malformed.close();pass('Malformed stored theme falls back safely to the default palette');
 if(!process.env.BILGE_TEST_ORIGIN){mode='v20';const legacy=await browser.newContext(),lp=await legacy.newPage();await lp.goto(origin);await saved(lp);await lp.waitForFunction(()=>document.querySelector('#pwaStatus').textContent.includes('paket hazır'));await lp.reload();await saved(lp);assert.match(await lp.locator('.badge').textContent(),/v20/);const original=await lp.evaluate(()=>dbGet());mode='v39';await lp.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await new Promise(async(resolve,reject)=>{const timer=setTimeout(()=>reject(Error('upgrade timeout')),30000);r.addEventListener('updatefound',()=>{const w=r.installing;w.addEventListener('statechange',()=>{if(w.state==='installed'){clearTimeout(timer);resolve()}if(w.state==='redundant'){clearTimeout(timer);reject(Error('upgrade failed'))}})},{once:true});await r.update()})});assert.match(await lp.locator('.badge').textContent(),/v20/);await lp.close();const upgraded=await legacy.newPage();await upgraded.goto(origin);await saved(upgraded);assert.match(await upgraded.locator('.badge').textContent(),/v39/);assert.deepEqual(await upgraded.evaluate(()=>dbGet()),original);assert.equal(await upgraded.locator('#quickUndo').count(),1);await legacy.close();pass('Actual v20 cached package upgrades directly to v39 after all old windows close and preserves notes')}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:results.length,results,physicalTabletAcceptance:'pending'},null,2));
 }finally{await browser?.close();if(server)await new Promise(ok=>server.close(ok))}})().catch(e=>{console.error(e);process.exitCode=1});
