const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {chromium}=require('C:/Users/sevdi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=process.env.BILGE_TEST_ROOT||path.join(__dirname,'bilge-defter-test'),live=process.argv.includes('--live'),results=[],errors=[];let server,browser,mode='v40',origin=process.env.BILGE_TEST_ORIGIN||'https://klipper-2.tail1ade8e.ts.net:8443';
const mime={'.html':'text/html','.css':'text/css','.js':'application/javascript','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png','.svg':'image/svg+xml','.wasm':'application/wasm','.bcmap':'application/octet-stream','.ttf':'font/ttf','.pfb':'application/octet-stream'};
const push=results.push.bind(results);results.push=value=>{console.log(value);return push(value)};
async function file(url){const name=decodeURIComponent(new URL(url,'http://localhost').pathname).replace(/^\//,'')||'index.html';if(name.split('/').includes('..'))throw Error();let data=await fs.readFile(path.join(root,name));if(mode!=='v40'){
 if(name==='sw.js')data=Buffer.from(data.toString().replace("VERSION='v40'","VERSION='v41'"));
 if(name==='index.html')data=Buffer.from(data.toString().replaceAll('v40','v41'));
 if(name==='offline-assets.json'){const m=JSON.parse(data);m.version='v41';const sw=Buffer.from((await fs.readFile(path.join(root,'sw.js'),'utf8')).replace("VERSION='v40'","VERSION='v41'"));const index=Buffer.from((await fs.readFile(path.join(root,'index.html'),'utf8')).replaceAll('v40','v41'));m.files.find(f=>f.path==='index.html').sha256=crypto.createHash('sha256').update(index).digest('hex');m.files.find(f=>f.path==='sw.js').sha256=crypto.createHash('sha256').update(sw).digest('hex');data=Buffer.from(JSON.stringify(m))}
 if(mode==='broken'&&name==='pwa.js')data=Buffer.concat([data,Buffer.from('\n// incomplete deployment')]);
 }return {data,type:mime[path.extname(name)]||'application/octet-stream'}}
async function saved(p){await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Bu cihazda kaydedildi')}
async function tools(p){if(!await p.locator('#toolsDialog').evaluate(x=>x.open))await p.locator('#toolsToggle').click()}
async function closeTools(p){if(await p.locator('#toolsDialog').evaluate(x=>x.open))await p.locator('#toolsClose').click()}
async function draw(p){const r=await p.locator('#canvas').boundingBox();await p.mouse.move(r.x+90,r.y+150);await p.mouse.down();await p.mouse.move(r.x+270,r.y+160,{steps:8});await p.mouse.up();await saved(p)}
async function backup(p){await tools(p);const event=p.waitForEvent('download');await p.locator('#exportBtn').click();const b=JSON.parse(await fs.readFile(await (await event).path(),'utf8'));await closeTools(p);return b}
async function restore(p,b){await p.locator('#importFile').setInputFiles({name:'transfer.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(b))});await p.locator('#backupApply').click();await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Yedek geri yüklendi')}
async function checkUpdate(p){return p.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();if(r.waiting)return 'installed';await r.update();const end=Date.now()+30000;while(Date.now()<end){if(r.waiting)return 'installed';await new Promise(x=>setTimeout(x,200))}return 'none'})}
(async()=>{
 if(!live){server=http.createServer(async(req,res)=>{try{const f=await file(req.url);if(req.url.includes('sw.js'))console.log('SRV',req.url,mode,JSON.stringify(f.data.toString().match(/VERSION='v\\d+'/)?.[0]));res.writeHead(200,{'Content-Type':f.type,'Cache-Control':'no-store'});res.end(f.data)}catch(e){console.log('SRV-404',req.url,e.message);res.writeHead(404);res.end()}});await new Promise(ok=>server.listen(0,'127.0.0.1',ok));origin=`http://127.0.0.1:${server.address().port}`}
 browser=await chromium.launch({headless:true});const c=await browser.newContext({viewport:{width:1180,height:820},hasTouch:true});c.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));let p=await c.newPage();p.setDefaultTimeout(60000);const response=await p.goto(origin+'/?v=21');assert.equal(response.status(),200);if(live)assert.ok((await response.securityDetails()).issuer);await saved(p);assert.equal(await p.evaluate(()=>isSecureContext),true);await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>document.querySelector('#pwaStatus').textContent.includes('paket hazır'));
 const manifest=await p.evaluate(async()=> (await fetch('./manifest.webmanifest')).json());assert.equal(manifest.display,'standalone');assert.equal(manifest.scope,'./');for(const icon of manifest.icons)assert.equal(await p.evaluate(async src=>{const i=new Image();i.src=src;await i.decode();return i.naturalWidth},icon.src),Number(icon.sizes.split('x')[0]));const expected=await p.evaluate(async()=> (await fetch('./offline-assets.json')).json());await p.waitForFunction(async count=> (await (await caches.open('bilge-defter-test-v40')).keys()).length===count,expected.files.length,{timeout:60000});await p.reload();await saved(p);assert.equal(await p.evaluate(()=>!!navigator.serviceWorker.controller),true);const cd=await c.newCDPSession(p);const installability=await cd.send('Page.getInstallabilityErrors');assert.deepEqual(installability.installabilityErrors,[]);
 results.push('Secure context, standalone manifest, decoded 192/512 icons, browser installability and complete 213-file offline package verified');
 await c.setOffline(true);await p.goto(origin+'/?offline-check=1');await saved(p);await draw(p);const plain=await p.evaluate(()=>dbGet());await p.reload();await saved(p);assert.deepEqual(await p.evaluate(()=>dbGet()),plain);assert.equal(await p.evaluate(async()=>{try{await fetch('./network-probe-uncached',{signal:AbortSignal.timeout(3000)});return false}catch{return true}}),true);
 results.push('Offline navigation with a fresh query, actual drawing, saving and reload retain the same notes');
 await tools(p);await p.locator('#pdfOpen').click();await p.locator('#pdfFile').setInputFiles(path.join(__dirname,'pdf-dependency/sample.pdf'));await p.waitForFunction(()=>!!pdfPending&&!pdfBusy);assert.equal(await p.evaluate(()=>pdfPending.pages.length),14);await p.locator('#pdfApply').click();await saved(p);await p.waitForFunction(()=>pdfBackgroundReady());await draw(p);await p.evaluate(()=>setPdfZoom(2));await saved(p);const pdfState=await p.evaluate(()=>dbGet());await p.reload();await saved(p);await p.waitForFunction(()=>pdfBackgroundReady());assert.deepEqual(await p.evaluate(()=>dbGet()),pdfState);assert.ok(await p.locator('#pdfCanvas').evaluate(c=>c.getContext('2d').getImageData(10,10,1,1).data[3]));
 results.push('With network disabled, local PDF.js and worker import a real 14-page PDF; PDF ink, zoom and background survive offline reload');
 const b=await backup(p);assert.equal(b.pages.length,15);await p.locator('#sidebarToggle').click();await p.locator('#newPage').click();await saved(p);await restore(p,b);assert.deepEqual((await p.evaluate(()=>dbGet())).pages,b.pages);await p.reload();await saved(p);assert.deepEqual((await p.evaluate(()=>dbGet())).pages,b.pages);
 results.push('Offline JSON download and confirmed file restore preserve PDF pages and notes across reload');
 await tools(p);await p.locator('#pwaOpen').click();await p.setViewportSize({width:390,height:844});const rect=await p.locator('#pwaDialog').boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=390&&rect.y>=0&&rect.y+rect.height<=844);await p.evaluate(()=>{window.__update=ServiceWorkerRegistration.prototype.update;ServiceWorkerRegistration.prototype.update=()=>Promise.reject(Error('injected network failure'))});await p.locator('#pwaCheck').click();await p.waitForFunction(()=>document.querySelector('#pwaUpdate').textContent.includes('denetlenemedi'));await p.screenshot({path:path.join(__dirname,`bilge-defter-v40-pwa-${live?'live':'local'}.png`),fullPage:true});await p.evaluate(()=>ServiceWorkerRegistration.prototype.update=window.__update);await p.locator('#pwaClose').click();await p.setViewportSize({width:1180,height:820});assert.deepEqual((await p.evaluate(()=>dbGet())).pages,b.pages);
 results.push('390px setup dialog fits, explains per-origin transfer and backup, and injected update failure does not change notes');
 await c.setOffline(false);const legacy=await browser.newContext({serviceWorkers:'block'});await legacy.route('http://pwa-transfer.invalid/**',async r=>{try{const f=await file(r.request().url());await r.fulfill({body:f.data,contentType:f.type})}catch{await r.fulfill({status:404,body:''})}});const old=await legacy.newPage();await old.goto('http://pwa-transfer.invalid/');await saved(old);assert.equal(await old.evaluate(()=>isSecureContext),false);assert.match(await old.locator('#pwaStatus').textContent(),/HTTP/);await draw(old);const oldData=await old.evaluate(()=>dbGet()),oldBackup=await backup(old);await restore(p,oldBackup);assert.deepEqual((await p.evaluate(()=>dbGet())).pages,oldData.pages);assert.deepEqual(await old.evaluate(()=>dbGet()),oldData);assert.deepEqual((await p.evaluate(()=>dbGet('before-import'))).pages,b.pages);await legacy.close();
 results.push('Insecure HTTP shows accurate no-offline warning; explicit cross-origin JSON migration preserves source notes and destination recovery copy');
 if(!live){
  await p.evaluate(()=>caches.open('unrelated-app-cache'));mode='broken';assert.equal(await checkUpdate(p),'none');assert.equal(await p.evaluate(async()=>!!(await navigator.serviceWorker.getRegistration()).waiting),false);assert.equal(await p.evaluate(()=>caches.has('bilge-defter-test-v41')),false);await c.setOffline(true);await p.reload();await saved(p);assert.match(await p.locator('.badge').textContent(),/v40/);assert.deepEqual((await p.evaluate(()=>dbGet())).pages,oldData.pages);await c.setOffline(false);
  results.push('Corrupt update asset fails integrity check, leaves no partial new cache, and the previous offline app and notes remain usable');
  mode='v40';const right=await c.newPage();await right.goto(origin+'/');await saved(right);mode='v41';assert.equal(await checkUpdate(p),'installed');console.log('Update installed and waiting');assert.match(await p.locator('.badge').textContent(),/v40/);assert.match(await right.locator('.badge').textContent(),/v40/);assert.equal(await p.evaluate(async()=>!!(await navigator.serviceWorker.getRegistration()).waiting),true);await p.locator('#toolsToggle').click();await p.locator('#pwaOpen').click();assert.equal(await p.locator('#pwaCheck').textContent(),'Güncellemeyi yükle');assert.match(await p.locator('#pwaUpdate').textContent(),/Yeni sürüm hazır/);await p.locator('#pwaClose').click();await right.close();await p.locator('#toolsToggle').click();await p.locator('#pwaOpen').click();await p.locator('#pwaCheck').click();await p.waitForFunction(()=>document.querySelector('.badge').textContent.includes('v41'));await saved(p);assert.deepEqual((await p.evaluate(()=>dbGet())).pages,oldData.pages);assert.equal(await p.evaluate(()=>caches.has('unrelated-app-cache')),true);assert.equal(await p.evaluate(()=>caches.has('bilge-defter-test-v40')),false);await c.setOffline(true);await p.reload();await saved(p);assert.match(await p.locator('.badge').textContent(),/v41/);
  results.push('Valid update installs completely, the setup dialog offers Güncellemeyi yükle, one click closes the last old window and opens the new version with notes and unrelated caches preserved');
 }
 assert.deepEqual(errors,[]);await c.close();console.log(JSON.stringify({mode:live?'live-HTTPS':'local-secure-loopback',passed:results.length,results,physicalDeviceInstallation:'pending'},null,2));
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)server.close()});
