const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'bilge-defter-invited-v48'),origin='http://127.0.0.1:49205';let browser;const results=[];
const pass=name=>{results.push(name);console.log('PASS '+name)};
async function context(){const c=await browser.newContext({serviceWorkers:'block',viewport:{width:1440,height:1000}});await c.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin!==origin)return route.abort();const file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return route.fulfill({status:404,body:''});return route.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'})[path.extname(file)]||'application/octet-stream'})});return c}
async function ready(p){await p.waitForFunction(()=>typeof ready!=='undefined'&&ready&&window.BilgeButtonThemeInstallation&&window.__v2UI)}
(async()=>{try{
 browser=await chromium.launch({headless:true});const c=await context(),p=await c.newPage(),errors=[];c.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await ready(p);const ui=p.locator('bilge-defter-ui');
 const paper=await p.locator('.paper').boundingBox();assert.ok(paper.width<=842&&Math.abs(paper.x-(1440-paper.width)/2)<2);assert.equal(await p.locator('.edge-actions').isVisible(),false);assert.equal(await p.locator('.app > header').isVisible(),false);assert.equal(await p.evaluate(()=>document.querySelector('.edge-actions').inert),true);pass('Desktop reference: centered 840px paper and no invisible old action overlays');
 await ui.locator('[data-panel="insert"]').click();await ui.locator('[data-command="insert.text"]').click();await p.locator('#layoutText').fill('Düşüncelerime yer açıyorum.\n\nBugünün notu\nKüçük adımlar, düzenli ilerleme.');await p.locator('#layoutDone').click();await p.evaluate(()=>flushSave());
 const note=await p.evaluate(()=>JSON.stringify(page().strokes));await ui.locator('[data-panel="settings"]').click();assert.equal(await ui.locator('[data-bdt-preset]').count(),6);
 for(const id of ['orman','gece','bilge','murdum','kehribar','grafit']){await ui.locator(`[data-bdt-preset="${id}"]`).click();const match=await p.evaluate(()=>{const a=document.querySelector('bilge-defter-ui').buttonTheme.getSnapshot(),b=BilgeButtonThemeInstallation.controller.getSnapshot();return a.preset===b.preset&&JSON.stringify(a.theme)===JSON.stringify(b.theme)&&getComputedStyle(document.documentElement).getPropertyValue('--bd-btn-primary-bg')===getComputedStyle(document.querySelector('bilge-defter-ui')).getPropertyValue('--bd-btn-primary-bg')});assert.ok(match,id)}
 assert.equal(await p.evaluate(()=>JSON.stringify(page().strokes)),note);pass('All six ZIP themes apply to both new toolbar and native engine dialogs without changing notes');
 await ui.locator('[data-bdt-preset="murdum"]').click();await p.screenshot({path:path.resolve(__dirname,'../outputs/bilge-defter-v48-tema.png'),fullPage:true});await p.keyboard.press('Escape');await p.reload();await ready(p);assert.equal(await p.evaluate(()=>document.querySelector('bilge-defter-ui').buttonTheme.getSnapshot().preset),'murdum');assert.equal(await p.evaluate(()=>JSON.stringify(page().strokes)),note);pass('Theme and synthetic note survive reload independently');
 const q=await c.newPage();await q.goto(origin);await ready(q);await p.evaluate(()=>document.querySelector('bilge-defter-ui').buttonTheme.usePreset('bilge'));await q.waitForFunction(()=>document.querySelector('bilge-defter-ui').buttonTheme.getSnapshot().preset==='bilge');assert.equal(await q.evaluate(()=>BilgeButtonThemeInstallation.controller.getSnapshot().preset),'bilge');await q.close();pass('Theme preference propagates to both controllers in a second tab');
 await ui.locator('[data-panel="study"]').click();await ui.locator('[data-command="study.dictionary"]').click();assert.equal(await p.locator('#dictDialog').evaluate(d=>d.open),true);await p.locator('#dictClose').click();await p.waitForFunction(()=>document.activeElement===document.querySelector('bilge-defter-ui'));pass('Dictionary opens from the new menu and closing restores visible keyboard focus');
 await ui.locator('[data-panel="library"]').click();await ui.locator('#bdx-page-search').pressSequentially('test');assert.equal(await p.evaluate(()=>mediaPending),null);assert.equal(await p.evaluate(()=>tool),'pen');await ui.locator('[data-close-panel]').click();pass('Typing inside shadow-DOM panels does not activate editor shortcuts');
 await ui.locator('[data-panel="settings"]').click();const paperColor=await p.evaluate(()=>page().paperColor||'#fffdf8');await ui.locator('[data-custom-frame]').fill('#243c5a');await ui.locator('[data-custom-frame]').dispatchEvent('change');assert.equal(await p.evaluate(()=>localStorage.getItem('bilge-defter-frame-v1')),'#243c5a');assert.equal(await p.evaluate(()=>page().paperColor||'#fffdf8'),paperColor);await p.keyboard.press('Escape');pass('Frame color changes independently from paper and ink');
 await p.evaluate(()=>document.querySelector('bilge-defter-ui').buttonTheme.usePreset('orman'));await p.screenshot({path:path.resolve(__dirname,'../outputs/bilge-defter-v48-masaustu.png'),fullPage:true});
 for(const width of [390,320]){await p.setViewportSize({width,height:844});await ui.locator('button[data-panel="settings"]').click();const box=await ui.locator('dialog[data-panel="settings"]').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width+1);await p.keyboard.press('Escape');const canvas=await p.locator('#canvas').boundingBox(),tool=await ui.locator('[data-v2-tool="pen"]').boundingBox();assert.ok(tool.y>=canvas.y+canvas.height-1);if(width===390)await p.screenshot({path:path.resolve(__dirname,'../outputs/bilge-defter-v48-telefon.png'),fullPage:true})}pass('320px and 390px layouts keep settings on-screen and writing tools outside the paper');
 const canvasIdentity=await p.evaluate(()=>{window.__originalCanvas=document.querySelector('#canvas');window.__v2UI.destroy();return window.__originalCanvas===document.querySelector('#canvas')&&!document.querySelector('bilge-defter-ui')&&!document.querySelector('.edge-actions').inert});assert.ok(canvasIdentity);assert.equal(await p.evaluate(()=>JSON.stringify(page().strokes)),note);pass('UI rollback preserves the original canvas, note data and visible legacy controls');
 assert.deepEqual(errors,[]);await c.close();
 const legacy=await context(),l=await legacy.newPage();await l.goto(origin);await ready(l);await l.evaluate(()=>{localStorage.removeItem('bilge-defter-button-theme-v1');localStorage.setItem('bilge-defter-ui-v2-button-theme-v1',JSON.stringify(BilgeButtonTheme.fromPreset('kehribar')))});await l.reload();await ready(l);assert.equal(await l.evaluate(()=>document.querySelector('bilge-defter-ui').buttonTheme.getSnapshot().preset),'kehribar');assert.equal(await l.evaluate(()=>BilgeButtonThemeInstallation.controller.getSnapshot().preset),'kehribar');await legacy.close();pass('Existing V2-only preference migrates when the production preference is absent');
 console.log(JSON.stringify({passed:results.length,failed:0,version:'v48',physicalDevices:'not tested'}));
}catch(error){console.error(error);process.exitCode=1}finally{await browser?.close()}})();
