const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http');
const {chromium}=require('C:/Users/sevdi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.join(__dirname,'bilge-defter-invited-v44'),results=[];let server,browser;
const types={'.html':'text/html','.css':'text/css','.js':'application/javascript','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png','.svg':'image/svg+xml','.wasm':'application/wasm'};
async function saved(p){await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Bu cihazda kaydedildi')}
async function tools(p){if(!await p.locator('#toolsDialog').evaluate(d=>d.open))await p.locator('#toolsToggle').click()}
async function closeTools(p){if(await p.locator('#toolsDialog').evaluate(d=>d.open))await p.locator('#toolsClose').click()}
async function clickPoint(p,x,y){const r=await p.locator('#canvas').boundingBox();await p.mouse.click(r.x+x,r.y+y)}
async function edit(p,x,y){await tools(p);await p.locator('#mediaEdit').click();await clickPoint(p,x,y);await p.locator('#layoutEdit').click();await p.locator('#mediaDialog').waitFor({state:'visible'})}
async function backup(p){await tools(p);const d=p.waitForEvent('download');await p.locator('#exportBtn').click();const b=JSON.parse(await fs.readFile(await(await d).path(),'utf8'));await closeTools(p);return b}
async function importBook(p,b){await p.locator('#importFile').setInputFiles({name:'media.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(b))});await p.locator('#backupApply').click();await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Yedek geri yüklendi')}
function pass(s){results.push(s);console.log(s)}
(async()=>{try{
 server=http.createServer(async(req,res)=>{try{const name=new URL(req.url,'http://local').pathname.slice(1)||'index.html';if(name.includes('..'))throw Error();const data=await fs.readFile(path.join(root,name));res.writeHead(200,{'Content-Type':types[path.extname(name)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data)}catch{res.writeHead(404);res.end()}});await new Promise(ok=>server.listen(0,'127.0.0.1',ok));
 const origin=process.env.BILGE_TEST_ORIGIN||`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch({headless:true});const c=await browser.newContext({viewport:{width:1180,height:820},hasTouch:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(15000);
 await p.goto(origin);await saved(p);await p.waitForFunction(()=>document.querySelector('#pwaStatus').textContent.includes('paket hazır'));await p.reload();await saved(p);
 await p.keyboard.press('t');await p.locator('#layoutText').fill('Türkçe not: ığüşöç İĞÜŞÖÇ\n<img src=x onerror=alert(1)>');await p.locator('#layoutDone').click();await saved(p);
 assert.equal(await p.evaluate(()=>state.version),3);assert.match(await p.evaluate(()=>page().strokes[0].text),/Türkçe/);assert.equal(await p.locator('img[src=x]').count(),0);pass('Hardware shortcut and keyboard text save as literal Turkish multiline content, no HTML execution');
 await p.reload();await saved(p);assert.equal(await p.evaluate(()=>page().strokes[0].tool),'text');
 await edit(p,35,55);await p.locator('#mediaText').fill('Düzenlenmiş metin');await p.locator('#mediaFont').fill('32');await p.locator('#mediaPlace').click();await clickPoint(p,130,160);await p.locator('#mediaApply').click();await saved(p);
 assert.equal(await p.evaluate(()=>page().strokes.length),1);assert.equal(await p.evaluate(()=>page().strokes[0].points[0].x),130);pass('Text edit, font size and explicit canvas placement preserve position without accidental ink');
 await p.keyboard.press('Control+z');await saved(p);assert.match(await p.evaluate(()=>page().strokes[0].text),/Türkçe/);
 const r=await p.locator('#canvas').boundingBox();await p.mouse.move(r.x+70,r.y+260);await p.mouse.down();await p.mouse.move(r.x+200,r.y+270);await p.mouse.up();await saved(p);await p.keyboard.press('Control+z');await saved(p);assert.equal(await p.evaluate(()=>page().strokes.length),1);pass('Undo restores media edits and then removes only the latest later ink stroke');
 const image=await p.evaluate(()=>{const c=document.createElement('canvas');c.width=200;c.height=120;const x=c.getContext('2d');x.fillStyle='#cc2233';x.fillRect(0,0,200,120);x.fillStyle='#ffffff';x.fillRect(40,20,50,40);return c.toDataURL('image/png')});
 await tools(p);await p.locator('#imageFile').setInputFiles({name:'photo.png',mimeType:'image/png',buffer:Buffer.from(image.split(',')[1],'base64')});await p.locator('#layoutBar').waitFor({state:'visible'});await p.locator('#layoutWidth').fill('240');const paper=await p.locator('#canvas').boundingBox();await p.mouse.move(paper.x+44,paper.y+68);await p.mouse.down();await p.mouse.move(paper.x+100,paper.y+350,{steps:8});await p.mouse.up();await p.locator('#layoutDone').click();await saved(p);
 if(await p.locator('#mediaDialog').evaluate(d=>d.open))console.log(await p.evaluate(()=>({message:document.querySelector('#mediaMessage').textContent,valid:document.querySelector('#mediaForm').checkValidity(),available:mediaAvailable(),draft:mediaDraft?{tool:mediaDraft.tool,width:mediaDraft.width,imageWidth:mediaDraft.imageWidth,imageHeight:mediaDraft.imageHeight,valid:validMediaStroke(mediaDraft)}:null,invalid:[...document.querySelectorAll('#mediaForm :invalid')].map(x=>x.id)})));
 assert.equal(await p.locator('#mediaDialog').evaluate(d=>d.open),false);await p.waitForFunction(()=>[...mediaImages.values()].every(im=>im.complete&&im.naturalWidth));const b=await backup(p);assert.equal(b.backupVersion,5);assert.equal(b.pages[0].strokes[1].tool,'image');pass('Real PNG file picker, local raster normalization, resize and placement produce v5 backup with embedded image');
 await c.setOffline(true);await p.goto(origin+'/?offline-media');await saved(p);await p.waitForFunction(()=>[...mediaImages.values()].some(im=>im.complete&&im.naturalWidth));assert.deepEqual((await p.evaluate(()=>dbGet())).pages,b.pages);pass('Text and actual image redraw after offline navigation and reload');
 await tools(p);p.once('dialog',d=>d.accept());await p.locator('#clearPage').click();await saved(p);assert.equal(await p.evaluate(()=>page().strokes.length),0);assert.equal(await p.evaluate(()=>state.trash[0].page.strokes.length),2);await p.reload();await saved(p);assert.equal(await p.evaluate(()=>state.trash[0].page.strokes[1].tool),'image');await importBook(p,b);assert.deepEqual((await p.evaluate(()=>dbGet())).pages,b.pages);pass('Clear archives both content types persistently; JSON restore returns exact image and text');
 await edit(p,100,350);p.once('dialog',d=>d.accept());await p.locator('#mediaDelete').click();await saved(p);assert.equal(await p.evaluate(()=>page().strokes.length),1);await p.keyboard.press('Control+z');await saved(p);assert.equal(await p.evaluate(()=>page().strokes.length),2);pass('Object deletion and undo restore the original image');
 const invalid=structuredClone(b);invalid.pages[0].strokes[1].image='data:image/svg+xml,<svg onload=alert(1)></svg>';assert.equal(await p.evaluate(x=>validState(x),invalid),false);invalid.pages[0].strokes[1]=b.pages[0].strokes[1];invalid.version=2;assert.equal(await p.evaluate(x=>validState(x),invalid),false);pass('Remote/SVG content and media disguised as an older state format are rejected');
 await tools(p);await p.locator('#pdfOpen').click();await p.locator('#pdfFile').setInputFiles(path.join(__dirname,'pdf-dependency/sample.pdf'));await p.waitForFunction(()=>!!pdfPending&&!pdfBusy);await p.locator('#pdfApply').click();await saved(p);await p.waitForFunction(()=>pdfBackgroundReady());assert.equal(await p.evaluate(()=>state.version),3);assert.equal(await p.evaluate(()=>validState(state)),true);pass('Offline PDF import retains v3 media data instead of downgrading the document schema');
 await tools(p);await p.locator('#textAdd').click();await p.locator('#layoutText').fill('PDF üzerinde klavye notu');await p.locator('#layoutDone').click();await saved(p);assert.equal(await p.evaluate(()=>page().strokes[0].tool),'text');pass('Keyboard text can also be added on a PDF page');
 await p.setViewportSize({width:390,height:844});await tools(p);await p.locator('#textAdd').click();await p.locator('#layoutText').fill('Klavye ile kısa not');const box=await p.locator('#layoutBar').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390&&box.height<=820);await p.screenshot({path:path.join(__dirname,'bilge-defter-v35-media-mobile.png'),fullPage:true});await p.locator('#layoutCancel').click();pass('390px dialog fits and a cancelled draft does not alter saved content');
 await tools(p);await p.locator('#textAdd').click();await p.locator('#layoutText').fill('Kayit hata denemesi');const beforeFailure=await p.evaluate(()=>dbGet());
 await p.evaluate(()=>{window.originalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){const r=window.originalPut.apply(this,args);if(args[1]==='app')this.transaction.abort();return r}});await p.locator('#layoutDone').click();await p.waitForFunction(()=>saveFailed);assert.deepEqual(await p.evaluate(()=>dbGet()),beforeFailure);assert.equal(await p.evaluate(()=>page().strokes.at(-1).text),'Kayit hata denemesi');await p.evaluate(()=>IDBObjectStore.prototype.put=window.originalPut);await p.locator('#retrySave').click();await saved(p);assert.equal(await p.evaluate(async()=>(await dbGet()).pages.find(x=>x.id===activeId).strokes.at(-1).text),'Kayit hata denemesi');pass('Failed media save preserves prior disk data and unsaved text; retry commits it');
 const invalidImage=structuredClone(b);invalidImage.pages[0].strokes[1].image=invalidImage.pages[0].strokes[1].image.slice(0,66)+'AAAA';assert.equal(await p.evaluate(async x=>{try{await validateMediaImages(x);return true}catch{return false}},invalidImage),false);pass('Truncated image bytes are decoded and rejected before restore');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:results.length,results,physicalKeyboardAndTablet:'pending'},null,2));
 }finally{await browser?.close();if(server)await new Promise(ok=>server.close(ok))}})().catch(e=>{console.error(e);process.exitCode=1});
