const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {chromium}=require('C:/Users/sevdi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const origin=(process.env.BILGE_TEST_ORIGIN||'http://100.84.251.49:18788'),live=process.argv.includes('--live'),results=[],errors=[];let browser;
async function saved(p){await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Bu cihazda kaydedildi')}
async function data(p,key='app'){return p.evaluate(key=>dbGet(key),key)}
async function sidebar(p){if(!await p.locator('#pageSidebar').isVisible())await p.locator('#sidebarToggle').tap()}
async function menu(p,id){await sidebar(p);await p.locator(`.page-menu[data-page-id="${id}"]`).tap()}
async function remove(p,id,accept=true){await menu(p,id);p.once('dialog',d=>accept?d.accept():d.dismiss());await p.locator('#deletePage').click();if(accept)await saved(p);else await p.locator('#pageDialogClose').click()}
async function trash(p){await sidebar(p);await p.locator('#openTrash').tap()}
function card(p,id){return p.locator(`.trash-card[data-trash-id="${id}"]`)}
async function restore(p,id){await trash(p);await card(p,id).getByRole('button',{name:'Geri getir',exact:true}).tap();await saved(p)}
async function tools(p){await p.locator('#toolsToggle').tap()}
async function download(p,selector){const next=p.waitForEvent('download');await p.locator(selector).click();return JSON.parse(await fs.readFile(await (await next).path(),'utf8'))}
async function exportBook(p){if(await p.locator('#pageSidebar').isVisible())await p.locator('#sidebarClose').click();await tools(p);const b=await download(p,'#exportBtn');await p.locator('#toolsClose').click();return b}
async function importBook(p,book){await p.locator('#importFile').setInputFiles({name:'trash.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(book))});await p.locator('#backupApply').click();await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Yedek geri yüklendi')}
async function invalid(p,book){const old=await data(p),recovery=await data(p,'before-import'),next=p.waitForEvent('dialog');await p.locator('#importFile').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(book))});const d=await next;assert.match(d.message(),/Geçerli/);await d.accept();assert.deepEqual(await data(p),old);assert.deepEqual(await data(p,'before-import'),recovery)}
const ink={tool:'pen',color:'#173b36',width:4,points:[{x:90,y:2120,p:.5,t:1},{x:210,y:2140,p:.5,t:2}]};
const seed={version:1,pages:[{id:'p1',title:'Anatomi <b>not</b>',strokes:[ink],paperColor:'#e3efff',viewY:2000,notebookId:'anatomi'},{id:'p2',title:'İkinci',strokes:[]},{id:'p3',title:'Üçüncü',strokes:[]}],active:'p1',notebooks:[{id:'anatomi',title:'Anatomi'}],activeNotebook:'anatomi'};
function content(p){const {updated,...rest}=p;return rest}
(async()=>{
 browser=await chromium.launch({headless:true});const c=await browser.newContext({serviceWorkers: 'block',viewport:{width:1180,height:820},hasTouch:true});c.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 if(!live)await c.route(origin+'/**',async r=>{const n=new URL(r.request().url()).pathname.split('/').pop()||'index.html',types={'index.html':'text/html','media-workspace.js':'application/javascript','planner-workspace.js':'application/javascript','ui-workspace.js':'application/javascript','ui.css':'text/css','pwa.js':'application/javascript','pdf-workspace.js':'application/javascript','sw.js':'application/javascript','manifest.webmanifest':'application/manifest+json'};if(!types[n])return r.fulfill({status:404,body:''});await r.fulfill({body:await fs.readFile(path.join(__dirname,'bilge-defter-test',n)),contentType:types[n]})});
 const p=await c.newPage();await p.goto(origin+'/?v=20');await saved(p);await p.evaluate(book=>dbPut(book),seed);await p.reload();await saved(p);
 await remove(p,'p1',false);assert.deepEqual(await data(p),seed);await remove(p,'p1');let b=await data(p);assert.equal(b.pages.length,2);assert.equal(b.active,null);assert.deepEqual(b.trash[0].page,seed.pages[0]);assert.equal(b.trash[0].position,0);assert.ok(Number.isFinite(Date.parse(b.trash[0].deletedAt)));await p.reload();await saved(p);assert.deepEqual(await data(p),b);await trash(p);assert.equal(await card(p,'p1').locator('h3').innerText(),seed.pages[0].title);assert.equal(await card(p,'p1').locator('b').count(),0);await p.locator('#trashClose').click();
 results.push('Cancelled delete is unchanged; confirmed delete persists full page in Trash across reload; empty notebook is safe and markup titles render as text');
 await restore(p,'p1');b=await data(p);assert.equal(b.active,'p1');assert.equal(b.activeNotebook,'anatomi');assert.deepEqual(content(b.pages[0]),seed.pages[0]);assert.equal(b.trash.length,0);assert.equal(await p.evaluate(()=>viewY()),2000);assert.equal(await p.locator('.paper').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(227, 239, 255)');await p.reload();await saved(p);assert.deepEqual(await data(p),b);
 results.push('Restore preserves stable ID, ink, paper color, original position, notebook membership and scroll after reload');
 await remove(p,'p1');await sidebar(p);await p.locator('#editNotebook').click();p.once('dialog',d=>d.accept());await p.locator('#deleteNotebook').click();await saved(p);await trash(p);assert.match(await card(p,'p1').innerText(),/Eski defter yok/);await p.locator('#trashClose').click();await restore(p,'p1');b=await data(p);assert.equal(b.activeNotebook,'general');assert.equal(b.pages[0].notebookId,undefined);assert.deepEqual(b.pages[0].strokes,seed.pages[0].strokes);assert.match(await p.locator('#inputState').innerText(),/Genel/);
 results.push('Deleting the former empty notebook does not delete archived ink; restore falls back explicitly to General');
 await remove(p,'p1');await remove(p,'p2');await menu(p,'p3');assert.equal(await p.locator('#deletePage').isDisabled(),true);await p.locator('#pageDialogClose').click();const archived=await data(p),backup=await exportBook(p);assert.equal(backup.backupVersion,3);assert.deepEqual(backup.trash,archived.trash);await trash(p);p.once('dialog',d=>d.dismiss());await card(p,'p1').getByRole('button',{name:'Kalıcı sil'}).click();assert.deepEqual(await data(p),archived);p.once('dialog',d=>d.accept());await card(p,'p1').getByRole('button',{name:'Kalıcı sil'}).click();await saved(p);assert.deepEqual((await data(p)).pages.map(content),archived.pages.map(content));assert.deepEqual((await data(p)).trash.map(t=>t.page.id),['p2']);await p.reload();await saved(p);await importBook(p,backup);assert.deepEqual(await data(p),archived);await p.reload();await saved(p);await restore(p,'p1');assert.equal((await data(p)).pages[0].id,'p1');
 results.push('Last live page is protected; permanent delete requires confirmation and affects only selected trash item; format-3 file restores archived pages after permanent delete');
 await importBook(p,backup);const legacy={version:1,pages:[{id:'old',title:'Eski',strokes:[]}],active:'old'};await importBook(p,legacy);assert.equal((await data(p)).trash,undefined);await tools(p);p.once('dialog',d=>d.accept());await p.locator('#restorePrevious').click();await p.waitForFunction(()=>document.querySelector('#saveState').textContent==='Önceki defter geri getirildi');if(await p.locator('#toolsDialog').evaluate(d=>d.open))await p.locator('#toolsClose').click();assert.deepEqual(await data(p),archived);
 results.push('Legacy backup remains compatible; import replaces trash explicitly and before-import recovery restores all archived pages');
 const bad=[null,{},[null],[{...backup.trash[0],deletedAt:'invalid'}],[{...backup.trash[0],position:-1}],[{...backup.trash[0],notebookTitle:null}],[{...backup.trash[0],page:{...backup.trash[0].page,paperColor:'url(bad)'}}],[{...backup.trash[0],page:{...backup.trash[0].page,strokes:[{...ink,width:0}]}}],[backup.trash[0],backup.trash[0]],[{...backup.trash[0],page:backup.pages[0]}]];
 for(const t of bad)await invalid(p,{...backup,trash:t});
 results.push('Malformed trash, bad page data, dates, positions and duplicate IDs are rejected without changing disk notes or recovery snapshot');
 await p.setViewportSize({width:390,height:844});await trash(p);let box=await p.locator('#trashDialog').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390);for(const button of await p.locator('.trash-actions button').all()){const r=await button.boundingBox();assert.ok(r.height>=44&&r.width>=44)}await p.screenshot({path:path.join(__dirname,`bilge-defter-v36-trash-${live?'live':'local'}.png`),fullPage:true});await p.locator('#trashClose').tap();await p.setViewportSize({width:844,height:390});await trash(p);await card(p,'p1').getByRole('button',{name:'Geri getir',exact:true}).tap();await saved(p);assert.equal((await data(p)).active,'p1');await p.setViewportSize({width:1180,height:820});
 results.push('Trash dialog fits narrow portrait with 44px touch targets; short-landscape tap restores page without clipping controls');
 for(const action of ['delete','restore','purge']){
  await importBook(p,backup);if(action==='delete')await restore(p,'p1');const before=await data(p);
  await p.evaluate(()=>{window.__put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){const r=window.__put.apply(this,args);if(args[1]==='app')this.transaction.abort();return r}});
  if(action==='delete'){await menu(p,'p1');p.once('dialog',d=>d.accept());await p.locator('#deletePage').click()}else{await trash(p);if(action==='purge')p.once('dialog',d=>d.accept());await card(p,'p1').getByRole('button',{name:action==='restore'?'Geri getir':'Kalıcı sil',exact:true}).click()}
  await p.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('Kaydedilemedi'));assert.deepEqual(await data(p),before);const emergency=await download(p,'#emergencyExport');assert.equal(emergency.trash.some(t=>t.page.id==='p1'),action==='delete');assert.equal(emergency.pages.some(x=>x.id==='p1'),action==='restore');await p.evaluate(()=>IDBObjectStore.prototype.put=window.__put);await p.locator('#retrySave').click();await saved(p);await p.reload();await saved(p);assert.deepEqual((await data(p)).trash,emergency.trash);assert.deepEqual((await data(p)).pages,emergency.pages);
 }
 results.push('Delete, restore and permanent-delete transaction failures each preserve prior disk state and support accurate emergency export plus retry/reload');
 await importBook(p,backup);const right=await c.newPage();await right.goto(origin+'/?v=20');await saved(right);await restore(p,'p1');const winning=await data(p);await trash(right);await card(right,'p2').getByRole('button',{name:'Geri getir',exact:true}).click();await right.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('Başka sekmede'));assert.deepEqual(await data(right),winning);const emergency=await download(right,'#emergencyExport');assert.equal(emergency.pages.some(x=>x.id==='p2'),true);
 results.push('Stale-tab trash restore cannot overwrite a newer save and retains its unsaved version in emergency export');
 assert.deepEqual(errors,[]);await c.close();console.log(JSON.stringify({mode:live?'live':'local',passed:results.length,results,physicalTabletTest:'pending'},null,2));
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close()});
