// The host owns accounts, persistence and ink. The opaque child receives only
// a COPY of one PPTX buffer; it never receives an account id or notebook data.
const MAX_BYTES=20*1024*1024,MAX_ID=0x7fffffff;
// Generated by prepare-pptx-pilot.cjs from the exact self-contained frame bytes.
const FRAME_HTML_SHA256='88f0fa99bf19e1170f944f73bd1fb656db860b213a7c2641527346abe918ddb6';
const MAX_FRAME_BYTES=4*1024*1024;
const ERROR_TEXT=Object.freeze({UNSUPPORTED:'Bu sunum güvenli okuyucuda desteklenmiyor.',LIMIT:'Sunum okuyucunun boyut veya karmaşıklık sınırını aşıyor.',TIMEOUT:'Sunum hazırlığı zaman sınırını aştı. Yeniden açmayı deneyin.',RENDER:'Slayt tam gösterilemedi. Özgün dosya ve notlar korunuyor.'});
const error=code=>Object.assign(new Error(ERROR_TEXT[code]||ERROR_TEXT.RENDER),{code:Object.hasOwn(ERROR_TEXT,code)?code:'RENDER'});
const record=value=>value!==null&&typeof value==='object'&&!Array.isArray(value);
const keys=(value,allowed)=>record(value)&&Object.keys(value).every(key=>allowed.includes(key));
const dimension=value=>typeof value==='number'&&Number.isFinite(value)&&value>=1&&value<=100000;
const warnings=value=>Array.isArray(value)&&value.length<=8&&value.every(item=>['experimental_layout','font_fallback_possible','links_disabled'].includes(item));
const validMeta=value=>keys(value,['slideCount','width','height','warnings'])&&Number.isSafeInteger(value.slideCount)&&value.slideCount>=1&&value.slideCount<=100&&dimension(value.width)&&dimension(value.height)&&value.height/value.width>=0.1&&value.height/value.width<=3&&warnings(value.warnings);
const validSlide=value=>keys(value,['index','width','height','warnings'])&&Number.isSafeInteger(value.index)&&value.index>=0&&value.index<100&&value.width===1000&&dimension(value.height)&&value.height>=100&&value.height<=3000&&warnings(value.warnings);

/**
 * createRenderer(container,{timeoutMs=20000}) -> Promise<renderer>
 * load(ArrayBuffer) retains caller ownership and returns intrinsic dimensions.
 * show(index) uses a zero-based index; the rendered surface is 1000 CSS px wide.
 * The host aligns/scales its ink canvas with renderer.element, not iframe DOM.
 * Timeout/protocol failures permanently dispose this instance; recreate it.
 */
export async function createRenderer(container,{timeoutMs=20000,signal}={}){
  if(!(container instanceof Element)||!Number.isFinite(timeoutMs)||timeoutMs<100||timeoutMs>60000)throw error('UNSUPPORTED');
  const token=[...crypto.getRandomValues(new Uint8Array(32))].map(byte=>byte.toString(16).padStart(2,'0')).join('');
  const frame=document.createElement('iframe');
  frame.title='PowerPoint slayt zemini';frame.setAttribute('aria-hidden','true');frame.tabIndex=-1;
  frame.setAttribute('sandbox','allow-scripts');frame.referrerPolicy='no-referrer';
  frame.setAttribute('allow',"camera 'none'; microphone 'none'; geolocation 'none'; clipboard-read 'none'; clipboard-write 'none'; fullscreen 'none'");
  frame.style.cssText='display:block;border:0;width:1000px;height:1px;pointer-events:none;user-select:none';
  let port=null,closed=false,connected=false,offered=false,serial=0,pending=null,meta=null,bootTimer;
  let resolveBoot,rejectBoot;
  const boot=new Promise((resolve,reject)=>{resolveBoot=resolve;rejectBoot=reject;});
  const bootFetch=new AbortController();
  const abortBoot=()=>dispose(error('RENDER'));
  function dispose(reason=error('RENDER')){
    if(closed)return;closed=true;clearTimeout(bootTimer);window.removeEventListener('message',hello);
    bootFetch.abort();signal?.removeEventListener('abort',abortBoot);
    if(pending){clearTimeout(pending.timer);pending.reject(reason);pending=null;}
    try{port?.close();}catch{}port=null;frame.remove();meta=null;
    if(!connected)rejectBoot(reason);
  }
  function receive(event){
    const data=event.data;
    if(closed)return;
    if(!connected){
      if(!keys(data,['v','id','type'])||data.v!==1||data.id!==0||data.type!=='connected'){dispose();return;}
      connected=true;clearTimeout(bootTimer);resolveBoot();return;
    }
    if(!pending||!keys(data,['v','id','ok','value','code'])||data.v!==1||data.id!==pending.id||typeof data.ok!=='boolean'){dispose();return;}
    const own=pending;pending=null;clearTimeout(own.timer);
    if(!data.ok){if(!keys(data,['v','id','ok','code'])||!Object.hasOwn(ERROR_TEXT,data.code)){own.reject(error('RENDER'));dispose();return;}own.reject(error(data.code));return;}
    if(!keys(data,['v','id','ok','value'])||!(own.command==='load'?validMeta(data.value):validSlide(data.value))){own.reject(error('RENDER'));dispose();return;}
    if(own.command==='show'&&(data.value.index!==own.index||!meta||data.value.index>=meta.slideCount)){own.reject(error('RENDER'));dispose();return;}
    own.resolve(Object.freeze({...data.value,warnings:Object.freeze([...data.value.warnings])}));
  }
  function hello(event){
    if(closed||offered||event.source!==frame.contentWindow||event.origin!=='null')return;
    if(!keys(event.data,['type','token'])||event.data.type!=='bilge-pptx-ready'||event.data.token!==token)return;
    offered=true;window.removeEventListener('message',hello);
    const channel=new MessageChannel();port=channel.port1;port.onmessage=receive;port.onmessageerror=()=>dispose();port.start();
    frame.contentWindow.postMessage({type:'bilge-pptx-connect',token},'*',[channel.port2]);
  }
  function rpc(command,value,transfer=[]){
    if(closed||!connected||pending||serial>=MAX_ID)return Promise.reject(error('RENDER'));
    const id=++serial;
    return new Promise((resolve,reject)=>{
      pending={id,command,index:value.index,resolve,reject,timer:setTimeout(()=>dispose(error('TIMEOUT')),timeoutMs)};
      try{port.postMessage({v:1,id,command,...value},transfer);}catch{dispose();}
    });
  }
  window.addEventListener('message',hello);
  signal?.addEventListener('abort',abortBoot,{once:true});
  bootTimer=setTimeout(()=>dispose(error('TIMEOUT')),timeoutMs);
  // Opaque sandbox navigations are not reliably served by the parent's service
  // worker offline. Fetch in the already controlled trusted parent, verify the
  // complete immutable document, then execute only those bytes in srcdoc.
  // The child keeps its hash-only CSP and has no network or storage privilege.
  void(async()=>{
    if(signal?.aborted){dispose();return;}
    const frameUrl=new URL('./renderer-frame.html',import.meta.url);
    if(frameUrl.origin!==location.origin)throw error('RENDER');
    const response=await fetch(frameUrl.href,{credentials:'same-origin',redirect:'error',cache:'no-store',referrerPolicy:'no-referrer',signal:bootFetch.signal});
    if(!response.ok||response.redirected||!/^text\/html(?:\s*;|$)/i.test(response.headers.get('content-type')||''))throw error('RENDER');
    const declared=response.headers.get('content-length');
    if(declared!==null&&(!/^\d+$/.test(declared)||Number(declared)>MAX_FRAME_BYTES))throw error('RENDER');
    const reader=response.body?.getReader();if(!reader)throw error('RENDER');
    const chunks=[];let size=0;
    try{
      while(true){const {done,value}=await reader.read();if(done)break;if(closed)throw error('RENDER');size+=value.byteLength;if(size>MAX_FRAME_BYTES)throw error('RENDER');chunks.push(value);}
    }finally{if(closed||size>MAX_FRAME_BYTES)void reader.cancel().catch(()=>{});try{reader.releaseLock();}catch{}}
    const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}
    const digest=await crypto.subtle.digest('SHA-256',bytes);
    const hash=[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('');
    if(closed)return;
    if(hash!==FRAME_HTML_SHA256)throw error('RENDER');
    const html=new TextDecoder('utf-8',{fatal:true}).decode(bytes);
    frame.name='bilge-pptx-'+token;frame.srcdoc=html;
    frame.addEventListener('error',()=>dispose(),{once:true});container.append(frame);
  })().catch(()=>dispose(error('RENDER')));
  try{await boot;}catch(cause){dispose(cause);throw cause;}
  return Object.freeze({element:frame,
    async load(bytes){
      if(!(bytes instanceof ArrayBuffer)||bytes.byteLength<8||bytes.byteLength>MAX_BYTES)throw error('LIMIT');
      const copy=bytes.slice(0);meta=null;
      const result=await rpc('load',{bytes:copy},[copy]);meta=result;
      frame.style.height=Math.ceil(1000*result.height/result.width)+'px';return result;
    },
    async show(index){
      if(!meta||!Number.isSafeInteger(index)||index<0||index>=meta.slideCount)throw error('UNSUPPORTED');
      return rpc('show',{index});
    },
    dispose(){dispose();},get disposed(){return closed;}
  });
}
