// Independently prepared pilot labels, not an imported dictionary/publication.
// Every mapping is DRAFT: reference candidates are not claims of source verification.
(function(root){
  'use strict';
  const rows = [
    ['heart','kalp','heart','cor','organ','yürek'],
    ['lung','akciğer','lung','pulmo','organ'],
    ['liver','karaciğer','liver','hepar','organ'],
    ['kidney','böbrek','kidney','ren','organ'],
    ['stomach','mide','stomach','gaster','organ'],
    ['spleen','dalak','spleen','splen','organ'],
    ['pancreas','pankreas','pancreas','pancreas','organ'],
    ['brain','beyin','brain','encephalon','sinir'],
    ['cerebellum','beyincik','cerebellum','cerebellum','sinir'],
    ['spinal-cord','omurilik','spinal cord','medulla spinalis','sinir'],
    ['trachea','soluk borusu','trachea','trachea','organ','nefes borusu'],
    ['oesophagus','yemek borusu','oesophagus','oesophagus','organ','özofagus','esophagus'],
    ['pharynx','yutak','pharynx','pharynx','organ','farinks'],
    ['larynx','gırtlak','larynx','larynx','organ','larinks'],
    ['diaphragm','diyafram','diaphragm','diaphragma','kas'],
    ['tongue','dil','tongue','lingua','organ'],
    ['tooth','diş','tooth','dens','organ'],
    ['skin','deri','skin','cutis','organ','cilt'],
    ['eye','göz','eye','oculus','organ'],
    ['ear','kulak','ear','auris','organ'],
    ['nose','burun','nose','nasus','organ'],
    ['urinary-bladder','idrar kesesi','urinary bladder','vesica urinaria','organ','mesane'],
    ['gallbladder','safra kesesi','gallbladder','vesica biliaris','organ'],
    ['small-intestine','ince bağırsak','small intestine','intestinum tenue','organ'],
    ['large-intestine','kalın bağırsak','large intestine','intestinum crassum','organ'],
    ['duodenum','onikiparmak bağırsağı','duodenum','duodenum','organ','on iki parmak bağırsağı'],
    ['rectum','rektum','rectum','rectum','organ'],
    ['thyroid','tiroit bezi','thyroid gland','glandula thyroidea','organ','tiroid bezi'],
    ['pituitary','hipofiz bezi','pituitary gland','hypophysis','organ','hipofiz'],
    ['adrenal','böbreküstü bezi','adrenal gland','glandula suprarenalis','organ','böbrek üstü bezi'],
    ['uterus','rahim','uterus','uterus','organ'],
    ['ovary','yumurtalık','ovary','ovarium','organ'],
    ['testis','testis','testis','testis','organ','er bezi'],
    ['prostate','prostat','prostate','prostata','organ'],
    ['ureter','üreter','ureter','ureter','organ'],
    ['urethra','üretra','urethra','urethra','organ'],
    ['skull','kafatası','skull','cranium','kemik'],
    ['mandible','alt çene kemiği','mandible','mandibula','kemik','mandibula'],
    ['maxilla','üst çene kemiği','maxilla','maxilla','kemik','maksilla'],
    ['frontal-bone','alın kemiği','frontal bone','os frontale','kemik'],
    ['parietal-bone','duvar kemiği','parietal bone','os parietale','kemik'],
    ['temporal-bone','şakak kemiği','temporal bone','os temporale','kemik'],
    ['occipital-bone','art kafa kemiği','occipital bone','os occipitale','kemik'],
    ['clavicle','köprücük kemiği','clavicle','clavicula','kemik','klavikula'],
    ['scapula','kürek kemiği','scapula','scapula','kemik','skapula'],
    ['sternum','göğüs kemiği','sternum','sternum','kemik'],
    ['rib','kaburga','rib','costa','kemik'],
    ['vertebra','omur','vertebra','vertebra','kemik'],
    ['vertebral-column','omurga','vertebral column','columna vertebralis','bölge','','spine'],
    ['sacrum','sağrı kemiği','sacrum','os sacrum','kemik','sakrum'],
    ['coccyx','kuyruk sokumu kemiği','coccyx','os coccygis','kemik','koksiks'],
    ['humerus','üst kol kemiği','humerus','humerus','kemik'],
    ['radius','döner kemik','radius','radius','kemik','radius'],
    ['ulna','dirsek kemiği','ulna','ulna','kemik','ulna'],
    ['femur','uyluk kemiği','femur','femur','kemik'],
    ['patella','diz kapağı kemiği','patella','patella','kemik'],
    ['tibia','kaval kemiği','tibia','tibia','kemik'],
    ['fibula','kamış kemiği','fibula','fibula','kemik'],
    ['talus','aşık kemiği','talus','talus','kemik'],
    ['calcaneus','topuk kemiği','calcaneus','calcaneus','kemik'],
    ['hip-bone','kalça kemiği','hip bone','os coxae','kemik'],
    ['hyoid','dil kemiği','hyoid bone','os hyoideum','kemik'],
    ['head','baş','head','caput','bölge'],
    ['neck','boyun','neck','collum','bölge'],
    ['thorax','göğüs','thorax','thorax','bölge','','chest'],
    ['abdomen','karın','abdomen','abdomen','bölge'],
    ['pelvis','pelvis','pelvis','pelvis','bölge','leğen'],
    ['back','sırt','back','dorsum','bölge'],
    ['arm','kol','arm','brachium','bölge','üst kol'],
    ['forearm','ön kol','forearm','antebrachium','bölge'],
    ['hand','el','hand','manus','bölge'],
    ['thigh','uyluk','thigh','femur','bölge'],
    ['leg','bacak','leg','crus','bölge'],
    ['foot','ayak','foot','pes','bölge'],
    ['knee','diz','knee','genu','bölge'],
    ['elbow','dirsek','elbow','cubitus','bölge'],
    ['deltoid','deltoid kası','deltoid muscle','musculus deltoideus','kas'],
    ['biceps-brachii','iki başlı kol kası','biceps brachii muscle','musculus biceps brachii','kas','biseps'],
    ['triceps-brachii','üç başlı kol kası','triceps brachii muscle','musculus triceps brachii','kas','triseps'],
    ['trapezius','trapez kası','trapezius muscle','musculus trapezius','kas'],
    ['latissimus-dorsi','geniş sırt kası','latissimus dorsi muscle','musculus latissimus dorsi','kas'],
    ['pectoralis-major','büyük göğüs kası','pectoralis major muscle','musculus pectoralis major','kas'],
    ['rectus-abdominis','düz karın kası','rectus abdominis muscle','musculus rectus abdominis','kas'],
    ['gluteus-maximus','büyük kalça kası','gluteus maximus muscle','musculus gluteus maximus','kas'],
    ['sartorius','terzi kası','sartorius muscle','musculus sartorius','kas'],
    ['gastrocnemius','gastroknemius kası','gastrocnemius muscle','musculus gastrocnemius','kas'],
    ['soleus','soleus kası','soleus muscle','musculus soleus','kas'],
    ['tibialis-anterior','ön tibial kas','tibialis anterior muscle','musculus tibialis anterior','kas'],
    ['masseter','çiğneme kası','masseter muscle','musculus masseter','kas','masseter'],
    ['sternocleidomastoid','sternokleidomastoid kas','sternocleidomastoid muscle','musculus sternocleidomastoideus','kas'],
    ['aorta','aort','aorta','aorta','damar'],
    ['artery','atardamar','artery','arteria','damar','arter'],
    ['vein','toplardamar','vein','vena','damar','ven'],
    ['nerve','sinir','nerve','nervus','sinir'],
    ['sciatic-nerve','siyatik sinir','sciatic nerve','nervus ischiadicus','sinir'],
    ['vagus-nerve','vagus siniri','vagus nerve','nervus vagus','sinir'],
    ['optic-nerve','görme siniri','optic nerve','nervus opticus','sinir','optik sinir'],
    ['median-nerve','median sinir','median nerve','nervus medianus','sinir'],
    ['acl','ön çapraz bağ','anterior cruciate ligament','ligamentum cruciatum anterius','bağ','ÖÇB','','ACL'],
    ['pcl','arka çapraz bağ','posterior cruciate ligament','ligamentum cruciatum posterius','bağ','AÇB','','PCL']
  ];
  const sources = [{id:'fipat-ta2',title:'FIPAT Terminologia Anatomica, 2. baskı (2019; 2020 kabulü)',url:'https://fipat.library.dal.ca/wp-content/uploads/2021/08/FIPAT-TA2-Front-Matter.pdf',role:'reference-candidate',rights:'Tekil terimler: kamu malı; yayın: CC BY-ND 4.0. Bu pilot yayının çevirisi değildir.'}];
  const notes = {
    arm:'Anatomik kol bölgesi omuz ile dirsek arasındadır; günlük kullanım daha geniş olabilir.',
    leg:'Anatomik bacak bölgesi diz ile ayak bileği arasındadır; günlük kullanım daha geniş olabilir.',
    thigh:'Uyluk bölgesi ve uyluk kemiği aynı kavram değildir. “Femur” araması ikisini de gösterebilir.',
    femur:'Kemik kavramıdır. Uyluk bölgesi kaydıyla karıştırmayın.',
    ureter:'Böbrek ile idrar kesesi arasındaki kanal; üretra ile karıştırmayın.',
    urethra:'İdrar kesesinden dışarı uzanan kanal; üreter ile karıştırmayın.',
    acl:'ACL kısaltması bu anatomi kapsamının dışında başka anlamlara gelebilir.',
    pcl:'PCL kısaltması bu anatomi kapsamının dışında başka anlamlara gelebilir.'
  };
  const data = {schemaVersion:1,version:'anatomy-pilot-1',scope:'Anatomi',reviewStatus:'draft',sources,concepts:rows.map(([id,tr,en,la,category,trAlias='',enAlias='',abbr=''])=>({
    id:'anatomy.'+id,category,labels:{tr,en,la},aliases:{tr:trAlias?[trAlias]:[],en:enAlias?[enAlias]:[],la:[]},abbreviations:abbr?[abbr]:[],
    note:notes[id]||'',reviewStatus:'draft',referenceCandidates:['fipat-ta2'],verifiedSources:[]
  }))};
  if(typeof module==='object'&&module.exports)module.exports=data;else root.BILGE_TERMINOLOGY_DATA=data;
})(typeof window==='object'?window:globalThis);
